TarOh/Models/OrdinalComment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TarOh.Models
{
    public class OrdinalComment
    {
        [Key]
        public int OrdinalCommentId { get; set; }

        public int OrdinalPositionId { get; set; }

        public string UserId { get; set; }

        public string Comment { get; set; }

        public ApplicationUser User { get; set; }

        public OrdinalPosition OrdinalPosition { get; set; }
    }
}

TarOh/Controllers/OrdinalCommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TarOh.Data;
using TarOh.Models;
using TarOh.Models.ViewModels;

namespace TarOh.Controllers
{
    public class OrdinalCommentsController : Controller
    {
        
        
            private readonly ApplicationDbContext _context;
            private readonly UserManager<ApplicationUser> _userManager;

            public OrdinalCommentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
            {
                _context = context;
                _userManager = userManager;
            }
            private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

            public async Task<IActionResult> GetUserOrdinalComments(int? id)
        {
            var user = await GetCurrentUserAsync();
            List<OrdinalCommentWithId> viewModelList = new List<OrdinalCommentWithId>();

            OrdinalCommentWithId ordinalCommentDataViewModel = new OrdinalCommentWithId
            {
                OrdinalComments = await _context.OrdinalComment
                .Include(o => o.OrdinalPosition)
                .Include(o => o.User)
                .Where(o => o.OrdinalPositionId == id && o.User.Id == user.Id).ToListAsync(),
                OrdinalPositionId = id,
                OrdinalPosition = _context.OrdinalPosition.Where(op => op.OrdinalPositionId == id).Last()
               

            };
            viewModelList.Add(ordinalCommentDataViewModel);

            

            return View( viewModelList.AsEnumerable());
        }
      

        // GET: OrdinalComments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordinalComment = await _context.OrdinalComment
                .Include(o => o.OrdinalPosition)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrdinalCommentId == id);
            if (ordinalComment == null)
            {
                return NotFound();
            }

            return View(ordinalComment);
        }

        // GET: OrdinalComments/Create
        public IActionResult Create(int id)
        {
            ViewData["OrdinalPositionId"] = id;
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: OrdinalComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("OrdinalCommentId,Comment")] OrdinalComment ordinalComment)
        {
            var user = await GetCurrentUserAsync();
            ordinalComment.OrdinalPositionId = id;
            ordinalComment.UserId = user.Id;
            if (ModelState.IsValid)
            {
                _context.Add(ordinalComment);
                await _context.SaveChangesAsync();
                return RedirectToAction("GetUserOrdinalComments", new { id = id });
            }
            
            
            return View(ordinalComment);
        }

        // GET: OrdinalComments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordinalComment = await _context.OrdinalComment.FindAsync(id);
            if (ordinalComment == null)
            {
                return NotFound();
            }
           
            return View(ordinalComment);
        }

        // POST: OrdinalComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrdinalCommentId,Comment")] OrdinalComment ordinalComment)
        {
            var user = await GetCurrentUserAsync();
            ordinalComment.UserId = user.Id;
            ordinalComment.OrdinalPositionId = _context.OrdinalComment.AsNoTracking().FirstOrDefault(oc => oc.OrdinalCommentId == id).OrdinalPositionId;
            if (id != ordinalComment.OrdinalCommentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ordinalComment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdinalCommentExists(ordinalComment.OrdinalCommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("GetUserOrdinalComments", new { id = ordinalComment.OrdinalPositionId });
            }
            ViewData["CardId"] = new SelectList(_context.Card, "CardId", "CardId", ordinalComment.OrdinalPositionId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", ordinalComment.UserId);
            return View(ordinalComment);
        }

        // GET: OrdinalComments/Delete/5
       

        // POST: OrdinalComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var ordinalComment = await _context.OrdinalComment.FindAsync(id);
            _context.OrdinalComment.Remove(ordinalComment);
            await _context.SaveChangesAsync();
            return RedirectToAction("GetUserOrdinalComments", new { id = ordinalComment.OrdinalPositionId });
        }

        private bool OrdinalCommentExists(int id)
        {
            return _context.OrdinalComment.Any(e => e.OrdinalCommentId == id);
        }
    }
}

TarOh/Views/OrdinalComments/Create.cshtml
@model TarOh.Models.OrdinalComment

@{
    ViewData["Title"] = "Create";
}
    <div class="bullshitcontainer">
        <div class="bullshit">
            

            <h1>Add an ordinal comment</h1>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="Comment" class="control-label"></label>
                            <input asp-for="Comment" class="form-control" />
                            <span asp-validation-for="Comment" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            
        </div>
    </div>

TarOh/Views/OrdinalComments/Delete.cshtml
@model TarOh.Models.OrdinalComment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrdinalComment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrdinalPosition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrdinalPosition.OrdinalPositionId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrdinalCommentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TarOh/Views/OrdinalComments/Edit.cshtml
@model TarOh.Models.OrdinalComment

@{
    ViewData["Title"] = "Edit";
}
<div class="bullshitcontainer">
    <div class="bullshit">
    <h1>Edit</h1>

    <h4>OrdinalComment</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="OrdinalCommentId" />

                <div class="form-group">
                    <label asp-for="Comment" class="control-label"></label>
                    <input asp-for="Comment" class="form-control" />
                    <span asp-validation-for="Comment" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>
</div>

TarOh/Views/OrdinalComments/GetUserOrdinalComments.cshtml
@model IEnumerable<TarOh.Models.ViewModels.OrdinalCommentWithId>

@{
    ViewData["Title"] = "GetUserOrdinalComments";
}
@{int? correctid = 0;}
    <div class="comments">
        


        @foreach (var item in Model)
        {
            correctid = item.OrdinalPositionId;


            <h2>My Comments: Position @item.OrdinalPosition.Name</h2>

        }
        <p>
            <a asp-action="Create" asp-route-id="@correctid">Add Comment</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Comment
                    </th>


                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {


                    @foreach (var ordinalcomment in item.OrdinalComments)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => ordinalcomment.Comment)
                            </td>


                            <td>
                                <a asp-action="Edit" asp-route-id="@ordinalcomment.OrdinalCommentId">Edit</a> |
                                <form asp-action="Delete" asp-controller="OrdinalComments" asp-route-id="@ordinalcomment.OrdinalCommentId" typeof="submit"><button type="submit" @*class="btn btn-danger"*@>Delete</button></form>
                            </td>
                        </tr>
                    }

                }

            </tbody>
        </table>
    </div>