TarOh/Models/CardComment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TarOh.Models
{
    public class CardComment
    {
        [Key]
        public int CardCommentId { get; set; }
        
        public int CardId { get; set; }

        public string UserId { get; set; }

        public string Comment { get; set; }

        public ApplicationUser User { get; set; }

        public Card Card { get; set; }
    }
}

TarOh/Controllers/CardCommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TarOh.Data;
using TarOh.Models;
using TarOh.Models.ViewModels;

namespace TarOh.Controllers
{
    public class CardCommentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CardCommentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: CardComments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CardComment.Include(c => c.Card).Include(c => c.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CardComments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cardComment = await _context.CardComment
                .Include(c => c.Card)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CardCommentId == id);
            if (cardComment == null)
            {
                return NotFound();
            }

            return View(cardComment);
        }

        public  async Task<IActionResult> GetUserCardComments( int? id)
        {
            Card card = _context.Card.Where(c => c.CardId == id).Last();
            int cardTypeId = card.CardTypeId;
            var user = await GetCurrentUserAsync();
            List<CardCommentWithId> viewModelList = new List<CardCommentWithId>();

            CardCommentWithId CardCommentDataViewModel = new CardCommentWithId
            {
                CardComments = await _context.CardComment
                .Include(cc => cc.Card)
                .ThenInclude(c => c.CardType)
                .Include(cc => cc.User)
                .Where(cc => cc.CardId == id && cc.User.Id == user.Id).ToListAsync(),
                CardId = id,
                Card = _context.Card.Where(c => c.CardId == id).Last(),
                CardType = _context.CardType.Where(ct => ct.CardTypeId == cardTypeId ).Last()


            };
            viewModelList.Add(CardCommentDataViewModel);



            return View(viewModelList.AsEnumerable());
            
        }

        // GET: CardComments/Create
        public IActionResult Create()
        {
            ViewData["CardId"] = new SelectList(_context.Card, "CardId", "CardId");
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: CardComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CardCommentId,CardId,UserId,Comment")] CardComment cardComment, int id)
        {
            var user = await GetCurrentUserAsync();
            cardComment.CardId = id;
            cardComment.UserId = user.Id;
            if (ModelState.IsValid)
            {
                _context.Add(cardComment);
                await _context.SaveChangesAsync();
                return RedirectToAction("GetUserCardComments", new { id = id });
            }
            
            return View(cardComment);
        }

        // GET: CardComments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var cardComment = await _context.CardComment.FindAsync(id);
            if (cardComment == null)
            {
                return NotFound();
            }
           

            return View(cardComment);
        }

        // POST: CardComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CardCommentId, Comment, UserId, CardId")] CardComment cardComment)
        {   var user = await GetCurrentUserAsync();
            cardComment.UserId = user.Id;
            cardComment.CardId = _context.CardComment.AsNoTracking().FirstOrDefault(cc => cc.CardCommentId == id).CardId;
            


            if (id != cardComment.CardCommentId)
            {
                return NotFound();
            }
           


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cardComment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CardCommentExists(cardComment.CardCommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("GetUserCardComments", new { id = cardComment.CardId });
            }
            
            return View(cardComment);
        }

        // GET: CardComments/Delete/5
        

        // POST: CardComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var cardComment = await _context.CardComment.FindAsync(id);
            _context.CardComment.Remove(cardComment);
            await _context.SaveChangesAsync();
            return RedirectToAction("GetUserCardComments", new { id = cardComment.CardId });
        }

        private bool CardCommentExists(int id)
        {
            return _context.CardComment.Any(e => e.CardCommentId == id);
        }
    }
}

TarOh/Views/CardComments/Create.cshtml
@model TarOh.Models.CardComment

@{
    ViewData["Title"] = "Create";
}
    <div class="bullshitcontainer">
        <div class="bullshit">
            <h1>Add A Card Comment</h1>

            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="Comment" class="control-label"></label>
                            <input asp-for="Comment" class="form-control" />
                            <span asp-validation-for="Comment" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

TarOh/Views/CardComments/Delete.cshtml
@model TarOh.Models.CardComment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CardComment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Card)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Card.CardId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CardCommentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TarOh/Views/CardComments/Details.cshtml
@model TarOh.Models.CardComment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CardComment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Card)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Card.CardId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CardCommentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TarOh/Views/CardComments/Edit.cshtml
@model TarOh.Models.CardComment

@{
    ViewData["Title"] = "Edit";
}

    <div class="bullshitcontainer">
        <div class="bullshit">
            <h1>Edit</h1>

            <h4>CardComment</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="CardCommentId" />

                        <div class="form-group">
                            <label asp-for="Comment" class="control-label"></label>
                            <input asp-for="Comment" class="form-control" />
                            <span asp-validation-for="Comment" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a asp-action="GetUserCardComments" asp-route-id="@Model.CardId">Back to List</a>
            </div>
        </div>
    </div>

TarOh/Views/CardComments/GetUserCardComments.cshtml
@model IEnumerable<TarOh.Models.ViewModels.CardCommentWithId>

@{
    ViewData["Title"] = "GetUserCardComments";
}
@{int? correctid = 0;}
    <div class="comments">
        


        @foreach (var item in Model)
        {
            correctid = item.CardId;


            <h1>My Comments: @item.CardType.Name</h1>

        }
        <p>
            <a asp-action="Create" asp-route-id="@correctid">Add Comment</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Comment
                    </th>


                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {


                    @foreach (var cardcomment in item.CardComments)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => cardcomment.Comment)
                            </td>


                            <td>
                                <a asp-action="Edit" asp-route-id="@cardcomment.CardCommentId">Edit</a> |
                                <form asp-action="Delete" asp-controller="CardComments" asp-route-id="@cardcomment.CardCommentId" typeof="submit"><button type="submit" @*class="btn btn-danger"*@>Delete</button></form>
                            </td>
                        </tr>
                    }

                }

            </tbody>
        </table>
    </div>

TarOh/Views/CardComments/Index.cshtml
@model IEnumerable<TarOh.Models.CardComment>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Card)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Card.CardId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CardCommentId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CardCommentId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CardCommentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>