TarOh/Models/Card.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TarOh.Models
{
    public class Card
    {
        [Key]
        public int CardId { get; set; }

        [DisplayName("Upload Image")]
        public string ImagePath { get; set; }

        public string UpDefinition { get; set; }

        public string DownDefinition { get; set; }

        public int CardTypeId { get; set; }

        public int DeckId { get; set; }

        public bool CardDirection { get; set; }

        public CardType CardType { get; set; }

        public List<CardComment> CardComments {get; set;}

        public List <SavedSpread> SavedSpreads { get; set; }

    }
}

TarOh/Models/CardType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TarOh.Models
{
    public class CardType
    {
        [Key]
        public int CardTypeId { get; set; }

        public string Name { get; set; }

       
    }
}

TarOh/Models/ViewModels/Reading.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TarOh.Models.ViewModels
{
    public class Reading
    {
        public List<Card> Cards { get; set; }

        public List<OrdinalPosition> OrdinalPositions { get; set;}

        public List<CardComment> CardComments { get; set; }

        public List<OrdinalComment> OrdinalComments { get; set; }

        public int SpreadId { get; set; }

        
    }
}

TarOh/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TarOh.Data;
using TarOh.Models;
using TarOh.Models.ViewModels;
using TarOh.Controllers;
using Microsoft.AspNetCore.Identity;
using System.Web;
using Microsoft.AspNetCore.Authorization;

namespace TarOh.Controllers
{
    public class CardsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CardsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public IActionResult SpreadName()
        {
            return View(); 
        }
        [Authorize]
        public async Task<IActionResult> Reading(int deckId, string name)
        {
            
            var user = await GetCurrentUserAsync();
            var applicationDbContext = _context.Card.Include(c => c.CardType);
            Random rand = new Random();
            var randomizedList = from item in applicationDbContext
                                 orderby rand.Next()
                                 select item;
            List<Reading> readingViewModelList = new List<Reading>();

            Reading readingViewModel = new Reading()
                {
                    Cards = await randomizedList.Take(11).ToListAsync(),
                    OrdinalPositions = await _context.OrdinalPosition.ToListAsync(),
                    OrdinalComments = await _context.OrdinalComment.Where( oc => oc.User.Id == user.Id).ToListAsync(),
                    CardComments = await _context.CardComment.Where( cc => cc.User.Id == user.Id).ToListAsync()
                };

            Spread dummySpread = new Spread()
                {
                    Name = name,
                    UserId = user.Id
                  };

                _context.Add(dummySpread);
                await _context.SaveChangesAsync();


                int count = 0;
                foreach (var card in readingViewModel.Cards)
                {
                    int ordinalId = count + 1;
                    Random rnd = new Random();
                    int cardDirection = rnd.Next(1, 3);

                if (cardDirection % 2 == 0)
                    {
                        card.CardDirection = true;
                    }
                    else
                    {
                        card.CardDirection = false;
                    }
                    SavedSpread dummySavedSpread = new SavedSpread()
                    {
                        SpreadId = dummySpread.SpreadId,
                        CardId = card.CardId,
                        OrdinalPositionId = ordinalId,
                        CardDirection = card.CardDirection,
                    };
                    _context.Add(dummySavedSpread);
                    await _context.SaveChangesAsync();

                    count++;
                }

            readingViewModel.SpreadId = dummySpread.SpreadId;
                readingViewModelList.Add(readingViewModel);

                return View(readingViewModelList.AsEnumerable());
            }

        // GET: Cards
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Card.Include(c => c.CardType);
            
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Cards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Card
                .Include(c => c.CardType)
                .FirstOrDefaultAsync(m => m.CardId == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // GET: Cards/Create
        public IActionResult Create()
        {
            ViewData["CardTypeId"] = new SelectList(_context.CardType, "CardTypeId", "CardTypeId");
            return View();
        }

        // POST: Cards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CardId,ImagePath,UpDefinition,DownDefinition,CardTypeId")] Card card)
        {
            if (ModelState.IsValid)
            {
                _context.Add(card);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CardTypeId"] = new SelectList(_context.CardType, "CardTypeId", "CardTypeId", card.CardTypeId);
            return View(card);
        }

        // GET: Cards/Edit/5
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Card.FindAsync(id);
            if (card == null)
            {
                return NotFound();
            }
            ViewData["CardTypeId"] = new SelectList(_context.CardType, "CardTypeId", "CardTypeId", card.CardTypeId);
            return View(card);
        }

        // POST: Cards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CardId,ImagePath,UpDefinition,DownDefinition,CardTypeId")] Card card)
        {
            if (id != card.CardId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(card);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CardExists(card.CardId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CardTypeId"] = new SelectList(_context.CardType, "CardTypeId", "CardTypeId", card.CardTypeId);
            return View(card);
        }

        // GET: Cards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Card
                .Include(c => c.CardType)
                .FirstOrDefaultAsync(m => m.CardId == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // POST: Cards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var card = await _context.Card.FindAsync(id);
            _context.Card.Remove(card);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CardExists(int id)
        {
            return _context.Card.Any(e => e.CardId == id);
        }
    }
}

TarOh/Views/Cards/Details.cshtml
@model TarOh.Models.Card

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Card</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpDefinition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpDefinition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DownDefinition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DownDefinition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CardType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CardType.CardTypeId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CardId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TarOh/Views/Cards/Edit.cshtml
@model TarOh.Models.Card

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Card</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CardId" />
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpDefinition" class="control-label"></label>
                <input asp-for="UpDefinition" class="form-control" />
                <span asp-validation-for="UpDefinition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DownDefinition" class="control-label"></label>
                <input asp-for="DownDefinition" class="form-control" />
                <span asp-validation-for="DownDefinition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardTypeId" class="control-label"></label>
                <select asp-for="CardTypeId" class="form-control" asp-items="ViewBag.CardTypeId"></select>
                <span asp-validation-for="CardTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TarOh/Views/Cards/SpreadName.cshtml
@{
    ViewData["Title"] = "SpreadName";
}
    <div class="bullshitcontainer">
        <div class="bullshit">
            <h1>Name This Spread</h1>

            @using (Html.BeginForm("Reading", "Cards"))
            {
                <input type="text" name="name" />

            }
        </div>
    </div>