TarOh/Models/SpreadComment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TarOh.Models
{
    public class SpreadComment
    {
        [Key]
        public int SpreadCommentId { get; set; }

        public int SpreadId { get; set; }

        public string UserId { get; set; }

        public string Comment { get; set; }

        public ApplicationUser User { get; set; }

        public Spread Spread { get; set; }
    }
}

TarOh/Controllers/SpreadCommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TarOh.Data;
using TarOh.Models;

namespace TarOh.Controllers
{
    public class SpreadCommentsController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SpreadCommentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IActionResult> GetUserSpreadComments(int id)
        {
            var user = await GetCurrentUserAsync();
            var applicaitonDbContext = _context.SpreadComment.Include(s => s.Spread).Where(s => s.UserId == user.Id && s.SpreadId == id);

            return View(await applicaitonDbContext.ToListAsync());
        }

        // GET: SpreadComments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.SpreadComment.Include(s => s.Spread).Include(s => s.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SpreadComments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spreadComment = await _context.SpreadComment
                .Include(s => s.Spread)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.SpreadCommentId == id);
            if (spreadComment == null)
            {
                return NotFound();
            }

            return View(spreadComment);
        }


        public IActionResult Create(int id)
        {
           
            return View();
        }

        // POST: SpreadComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("SpreadCommentId,Comment")] SpreadComment spreadComment)
        {
            var user = await GetCurrentUserAsync();
            spreadComment.SpreadId = id;
            spreadComment.UserId = user.Id;
            if (ModelState.IsValid)
            {
                _context.Add(spreadComment);
                await _context.SaveChangesAsync();
                return RedirectToAction("GetUserSpreadComments", new { id = id });
            }
         
            return View(spreadComment);
        }

        // GET: SpreadComments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spreadComment = await _context.SpreadComment.FindAsync(id);
            if (spreadComment == null)
            {
                return NotFound();
            }
           
            return View(spreadComment);
        }

        // POST: SpreadComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SpreadCommentId,Comment")] SpreadComment spreadComment)
        {
            var user = await GetCurrentUserAsync();
            spreadComment.UserId = user.Id;
            spreadComment.SpreadId = _context.SpreadComment.AsNoTracking().Where(sc => sc.UserId == user.Id && sc.SpreadCommentId == id).SingleOrDefault().SpreadId;
            if (id != spreadComment.SpreadCommentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spreadComment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpreadCommentExists(spreadComment.SpreadCommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("GetUserSpreadComments", new { id = spreadComment.SpreadId });
            }
           
            return View(spreadComment);
        }

        // GET: SpreadComments/Delete/5
     

        // POST: SpreadComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var spreadComment = await _context.SpreadComment.FindAsync(id);
            _context.SpreadComment.Remove(spreadComment);
            await _context.SaveChangesAsync();
            return RedirectToAction("GetUserSpreadComments", new { id = spreadComment.SpreadId});
        }

        private bool SpreadCommentExists(int id)
        {
            return _context.SpreadComment.Any(e => e.SpreadCommentId == id);
        }
    }
}

TarOh/Controllers/SpreadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TarOh.Data;
using TarOh.Models;

namespace TarOh.Controllers
{
    public class SpreadsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SpreadsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        // GET: Spreads
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Spread.Include(s => s.User);
            return View(await applicationDbContext.ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> MySavedSpreads()
        {
            var user = await GetCurrentUserAsync();

            var applicationDbContext = _context.Spread.Include(s => s.SavedSpreads)
                .Include(s => s.User)
                .Where(s => s.UserId == user.Id);
            
            return View(await applicationDbContext.ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> ViewSavedSpread(int? id)
        {
            var user = await GetCurrentUserAsync();

            var applicationDbContext = _context.Spread
                .Include(s => s.SavedSpreads)
                .ThenInclude(ss => ss.Card)
                .ThenInclude(ct => ct.CardType)
                .Include(s => s.SavedSpreads)
                .ThenInclude(ss => ss.Card)
                .ThenInclude(ct => ct.CardComments)
                .Include(s => s.SavedSpreads)
                .ThenInclude(ss => ss.OrdinalPosition)
                .ThenInclude(op => op.OrdinalComments)
                .Where(s => s.SpreadId == id);

             return View(await applicationDbContext.ToListAsync());
        }

        

        // GET: Spreads/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spread = await _context.Spread
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.SpreadId == id);
            if (spread == null)
            {
                return NotFound();
            }

            return View(spread);
        }

        // GET: Spreads/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Spreads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SpreadId,Name,ReadingDate,UserId")] Spread spread)
        {
            if (ModelState.IsValid)
            {
                _context.Add(spread);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", spread.UserId);
            return View(spread);
        }

        // GET: Spreads/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spread = await _context.Spread.FindAsync(id);
            if (spread == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", spread.UserId);
            return View(spread);
        }

        // POST: Spreads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SpreadId,Name,ReadingDate,UserId")] Spread spread)
        {
            if (id != spread.SpreadId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spread);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpreadExists(spread.SpreadId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", spread.UserId);
            return View(spread);
        }

        // GET: Spreads/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var spread = await _context.Spread
        //        .Include(s => s.User)
        //        .FirstOrDefaultAsync(m => m.SpreadId == id);
        //    if (spread == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(spread);
        //}

        // POST: Spreads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var user = GetCurrentUserAsync();
            var spread = await _context.Spread.FindAsync(id);
            _context.Spread.Remove(spread);
            await _context.SaveChangesAsync();
            return RedirectToAction("MySavedSpreads", new {id = user.Id });
        }

        private bool SpreadExists(int id)
        {
            return _context.Spread.Any(e => e.SpreadId == id);
        }
    }
}

TarOh/Views/SpreadComments/Create.cshtml
@model TarOh.Models.SpreadComment

@{
    ViewData["Title"] = "Create";
}
    <div class="bullshitcontainer">
        <div class="bullshit">
            

            <h1>Add A Spread Comment</h1>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="Comment" class="control-label"></label>
                            <input asp-for="Comment" class="form-control" />
                            <span asp-validation-for="Comment" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            
        </div>
    </div>

TarOh/Views/SpreadComments/Delete.cshtml
@model TarOh.Models.SpreadComment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SpreadComment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Spread)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Spread.SpreadId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SpreadCommentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TarOh/Views/SpreadComments/Details.cshtml
@model TarOh.Models.SpreadComment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SpreadComment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Spread)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Spread.SpreadId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SpreadCommentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TarOh/Views/SpreadComments/Edit.cshtml
@model TarOh.Models.SpreadComment

@{
    ViewData["Title"] = "Edit";
}
    <div class="bullshitcontainer">
        <div class="bullshit">
        <h1>Edit</h1>

        <h4>SpreadComment</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="SpreadCommentId" />

                    <div class="form-group">
                        <label asp-for="Comment" class="control-label"></label>
                        <input asp-for="Comment" class="form-control" />
                        <span asp-validation-for="Comment" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
    </div>

TarOh/Views/SpreadComments/GetUserSpreadComments.cshtml
@model IEnumerable<TarOh.Models.SpreadComment>

@{
    ViewData["Title"] = "GetUserSpreadComments";
}
<div class="comments">
<h1>My Spread Comments</h1>

<p>
    <a asp-action="Create" asp-route-id="@ViewContext.RouteData.Values["Id"]">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Spread)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Spread.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SpreadCommentId">Edit</a> |
                <a asp-controller="Spreads" asp-action="ViewSavedSpread" asp-route-id="@item.SpreadId">View Spread</a> |
                <form asp-action="Delete" asp-controller="SpreadComments" asp-route-id="@item.SpreadCommentId" typeof="submit"><button type="submit" >Delete</button></form>
            </td>
        </tr>
}
    </tbody>
</table>
    </div>